### PR TITLE
3 ➡️ 4

### PR DESCRIPTION
**Pull request by chapulina**

### CODE REVIEW

**Comment by ahcorde** [comment]
Some tests are failing on MacOS, there are some SEGFAULTs:

```
	  1 - UNIT_Application_TEST (SEGFAULT)
	  2 - check_UNIT_Application_TEST (Failed)
	 11 - UNIT_MainWindow_TEST (SEGFAULT)
	 12 - check_UNIT_MainWindow_TEST (Failed)
	 15 - UNIT_Plugin_TEST (SEGFAULT)
	 16 - check_UNIT_Plugin_TEST (Failed)
```

**Comment by adlarkin** [comment]
@chapulina can you by chance add in the recent changes from https://github.com/ignitionrobotics/ign-gui/pull/146? That way, we can include the codecheck fixes related to https://github.com/ignitionrobotics/ign-cmake/pull/117.

**Review by adlarkin — COMMENTED** [review]
The changes seem fine, but do we need to address the failing Mac OS tests that were mentioned [here](https://github.com/ignitionrobotics/ign-gui/pull/143#issuecomment-720947203) before completing the forward port?

**Comment by chapulina** [comment]
The homebrew tests aren't new, see https://github.com/ignitionrobotics/ign-gui/issues/123:

* `Application_TEST` [never passed for `ign-gui4`](https://build.osrfoundation.org/job/ignition_gui-ci-ign-gui4-homebrew-amd64/lastBuild/testReport/(root)/UNIT_Application_TEST/test_ran/history/)
* `Plugin_TEST` [never passed for `ign-gui4`](https://build.osrfoundation.org/job/ignition_gui-ci-ign-gui4-homebrew-amd64/lastBuild/testReport/(root)/UNIT_Plugin_TEST/test_ran/history/)
* `MainWindow_TEST`, interestingly, has [passed once](https://build.osrfoundation.org/job/ignition_gui-ci-ign-gui4-homebrew-amd64/lastBuild/testReport/(root)/MainWindowTest/history/). But I think it may be flaky :thinking: 

I triggered a new build for the `ign-gui4` branch to get more data points: [Build Status](https://build.osrfoundation.org/job/ignition_gui-ci-ign-gui4-homebrew-amd64/3/)

**Review by adlarkin — APPROVED** [review]
> The homebrew tests aren't new

Thanks for pointing this out and giving some more information. I'll go ahead and approve this to unblock you, since it seems like the failures aren't coming from this PR.

**Pull request merged**
