### PR TITLE
Bumps in garden : ign-gui7

### PR DESCRIPTION
**Pull request by scpeters**
See https://github.com/ignition-tooling/release-tools/issues/545

### CODE REVIEW

**Review by jennuine — COMMENTED** [review]
I haven't done bumps before, does there need to be a `ign-rendering7` prerelease before this is ready?

**Comment by scpeters** [comment]
> I haven't done bumps before, does there need to be a `ign-rendering7` prerelease before this is ready?

I ran a script that created all the pull requests at once. I'm going to update that script to do things in a better order

**Comment by chapulina** [comment]
> does there need to be a ign-rendering7 prerelease before this is ready?

Nope, we just need to enable CI to use nightlies

**Review by chapulina — APPROVED** [review]
LGTM with green CI

**Comment by scpeters** [comment]
> I retriggered the homebrew build now that [osrf/homebrew-simulation#1686](https://github.com/osrf/homebrew-simulation/pull/1686) is merged

:green_heart:

**Comment by scpeters** [comment]
some test failures in focal github action, but otherwise :green_apple:, so I'll merge

**Pull request merged**
