### PR TITLE
Prevent Scene3D 💥 if another scene is already loaded

### PR DESCRIPTION
**Pull request by chapulina**
# 🦟 Bug fix

* Part of https://github.com/ignitionrobotics/ign-gazebo/issues/1254

## Summary

Current issue:

1. Start `ign gazebo`
2. From the top-right menu, select `Scene 3D`
3. :boom: 

This PR prevents a crash and prints a message explaining to the user what happened.

image

The message will be printed if there's any other plugin already loading a render engine, so it's compatible with both `GzScene3D` and `Scene3D`.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Review by ahcorde — COMMENTED** [review]
Changes in these two files are unrelated:
 - src/plugins/scene3d/Scene3D.qml
 - test/integration/scene3d.cc

**Comment by chapulina** [comment]
> Changes in these two files are unrelated:
>    src/plugins/scene3d/Scene3D.qml

This is necessary to display a message to the user about why the plugin failed loading.

>    test/integration/scene3d.cc

At first I thought that this PR had made the tests less precise, so I relaxed the tolerances. I don't understand how that could be the case though, I think that test may be flaky even without that PR. I could break that into another PR if it's clearer, but since I have the approval I'll go ahead and merge now.

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-01-24-citadel-edifice-fortress/1241/1

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-01-citadel-edifice-fortress/1313/1

**Pull request merged**
