### PR TITLE
Removed duplicated code with rendering::sceneFromFirstRenderEngine

### PR DESCRIPTION
**Pull request by ahcorde**
# Enhancement
## Summary
Related to this PR in ignition-renderin https://github.com/ignitionrobotics/ign-rendering/pull/320#event-4749407284. It uses the helper function rendering::sceneFromFirstRenderEngine to get the first scene that can be found in any rendering engine.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by mjcarroll** [comment]
Looks like this will need a release of ign-rendering to pass CI.

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Comment by ahcorde** [comment]
@mjcarroll the UNIT_Application_TEST is failing buit I think it's unrelated

**Review by jennuine — APPROVED** [review]
LGTM

`UNIT_Application_TEST` is also failing in https://github.com/ignitionrobotics/ign-gui/pull/225 as well as locally for me but I don't understand why?

**Comment by mjcarroll** [comment]
I think that `UNIT_Application_TEST` is segfaulting at the end, which will cause it to fail.

**Comment by ahcorde** [comment]
In my local machine it's failing here:

```
auto ds = app.allWindows();
```

This should return only one element in the vector, but I'm getting 2.

**Comment by ahcorde** [comment]
As this test is unrelated to this PR I will merge it. It seems flaky

**Comment by jennuine** [comment]
> This should return only one element in the vector, but I'm getting 2.

It fails for me there too. I think it probably is flaky

**Comment by mboisson** [comment]
This PR broke the semantic versioning for Citadel. I was trying to build Citadel with the latest versions of each package, and this yields this error: 
https://github.com/ignitionrobotics/ign-gui/issues/263

**Pull request merged**
